import type { ChallengeState } from "./types";

export const FITNESS_INITIAL: ChallengeState = {
  eventName: "30-DAY IRON CHALLENGE",
  eventLabel: "Pure Fitness \u00b7 Live Challenge",
  subtitle: "30 Classes in 30 Days",
  region: "Singapore & Hong Kong \u00b7 March 2025",
  day: 18,
  totalDays: 30,
  unit: "Classes",
  participants: 147,
  todayCount: 43,
  totalClasses: 2841,
  entries: [
    { name: "Sarah T.", score: 24, location: "Singapore", change: 0 },
    { name: "Marcus L.", score: 22, location: "Hong Kong", change: 1 },
    { name: "Priya S.", score: 21, location: "Singapore", change: -1 },
    { name: "James W.", score: 20, location: "Hong Kong", change: 0 },
    { name: "Aiyana K.", score: 19, location: "Singapore", change: 2 },
    { name: "David C.", score: 18, location: "Hong Kong", change: 0 },
    { name: "Mei Lin", score: 17, location: "Singapore", change: -1 },
    { name: "Rachel H.", score: 16, location: "Singapore", change: 0 },
    { name: "Tom B.", score: 15, location: "Hong Kong", change: 1 },
    { name: "Fiona M.", score: 14, location: "Singapore", change: 0 },
  ],
  activities: [
    { name: "Marcus L.", detail: "Completed class", pts: "+1" },
    { name: "Aiyana K.", detail: "Completed class", pts: "+1" },
    { name: "Sarah T.", detail: "Completed class", pts: "+1" },
    { name: "Tom B.", detail: "Completed class", pts: "+1" },
    { name: "Priya S.", detail: "Completed class", pts: "+1" },
  ],
};

export const YOGA_INITIAL: ChallengeState = {
  eventName: "21-DAY YOGA CHALLENGE",
  eventLabel: "Pure Yoga \u00b7 Live Challenge",
  subtitle: "21 Yoga Classes in 21 Days",
  region: "Singapore & Hong Kong \u00b7 April 2025",
  day: 14,
  totalDays: 21,
  unit: "Classes",
  participants: 89,
  todayCount: 31,
  totalClasses: 1247,
  entries: [
    { name: "Priya S.", score: 18, location: "Singapore", change: 0 },
    { name: "Mei Lin", score: 17, location: "Hong Kong", change: 1 },
    { name: "Sarah T.", score: 16, location: "Singapore", change: -1 },
    { name: "Aiyana K.", score: 15, location: "Singapore", change: 0 },
    { name: "Rachel H.", score: 14, location: "Hong Kong", change: 2 },
    { name: "Fiona M.", score: 13, location: "Singapore", change: 0 },
    { name: "James W.", score: 12, location: "Hong Kong", change: -1 },
    { name: "Lena C.", score: 11, location: "Singapore", change: 0 },
    { name: "Tom B.", score: 10, location: "Hong Kong", change: 1 },
    { name: "David C.", score: 9, location: "Singapore", change: 0 },
  ],
  activities: [
    { name: "Priya S.", detail: "Completed Vinyasa Flow", pts: "+1" },
    { name: "Mei Lin", detail: "Completed Yin Yoga", pts: "+1" },
    { name: "Aiyana K.", detail: "Completed Power Yoga", pts: "+1" },
    { name: "Rachel H.", detail: "Completed Hatha", pts: "+1" },
    { name: "Sarah T.", detail: "Completed Restorative", pts: "+1" },
  ],
};
